### ISSUE TITLE
can't work on android 

### ISSUE THREAD

**Issue by Ali-Abbas-Jumaa** [TahaMalas/flutter_image_viewer#8]
When trying to use the Widget these errors are shown:

`E/MethodChannel#image_viewer(30540): Failed to handle method call
E/MethodChannel#image_viewer(30540): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:94)
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/MethodChannel#image_viewer(30540): 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/MethodChannel#image_viewer(30540): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/MethodChannel#image_viewer(30540): 	at android.app.Dialog.show(Dialog.java:313)
`

I am using these versions of SDKs: 
`Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (6 months ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0`
`android-x86 • Android 11 (API 30) (emulator)`

**Comment by Noble-Shiva** [comment]
https://github.com/flutter/flutter/issues/47602#issuecomment-574918810

This might help!

**Comment by lyseiha** [comment]
any update?

**Comment by Ali-Abbas-Jumaa** [comment]
> any update?
Yes, I solved it after @Noble-Shiva have shared this link.
https://github.com/flutter/flutter/issues/47602#issuecomment-574918810

**Comment by Ali-Abbas-Jumaa** [comment]
> [flutter/flutter#47602 (comment)](https://github.com/flutter/flutter/issues/47602#issuecomment-574918810)
> 
> This might help!

Thanks that works for me.

**Comment by Noble-Shiva** [comment]
> > [flutter/flutter#47602 (comment)](https://github.com/flutter/flutter/issues/47602#issuecomment-574918810)
> > This might help!
> 
> Thanks that works for me.

Happy to Help!

**Comment by TahaMalas** [comment]
Thanks @Ali-Abbas-Jumaa for contributing, this was actually a duplicate of issue #5
